services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=veemdb
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    expose:
      - 5432
  server:
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_PASSWORD=12345
      - DB_NAME=veemdb
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    links:
      - db
    depends_on:
      - db
  client:
    command: npm run dev
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    links:
      - server
    depends_on:
      - server
